### ISSUE TITLE
Feedback for “Getting started Open Micro SaaS, the Next.js SaaS template”

### ISSUE THREAD

**Issue by Venediktoff** [product-makers-hub/open-micro-saas-docs#1]
It might be worth mentioning that you need to use session mode (port 5432) when providing the database URL, before running npx prisma migrate dev.

I am using Superbase and it took me close to 4 hours to get to the point where it ran successfully.

**Comment by juan-carlos-correa** [comment]
> It might be worth mentioning that you need to use session mode (port 5432) when providing the database URL, before running npx prisma migrate dev.
> 
> I am using Superbase and it took me close to 4 hours to get to the point where it ran successfully.

Thank you for your feedback!

I would like to understand better what you mentioned, 

Do you mean the process of using a supabase DB connection, right? 

I did that in a private project using this template following this [supabase doc](https://supabase.com/partners/integrations/prisma), and got the things working, but probably my case was different than yours.

If possible, I'd love to hear more details about your case, 

- It was for local development? or production? 
- What kind of errors did you get?

Finally, what was the solution you used? I don't get at all the session mode that you mentioned.

**Comment by Venediktoff** [comment]
Hi. Sorry for the lack of details in my feedback. 

* I was using supabase cloud database. 
* By default supabase offers connection URI for transaction mode, with port 6543. 
* When using port 6543, `npx prisma migrate dev` does not work. 
* The only clue I found that the connection should be in session mode (port 5432) is by checking docker files in the root dir.

There were no errors, which cause the confusion. Prisma would display the connection URI in the terminal and that would be it. 

The documentation you linked to would be the saving grace in this situation. Maybe it's worth adding the link to the "getting started" page as a lot of people would like to use supabase, especially for small saas.

**Comment by juan-carlos-correa** [comment]
> Hi. Sorry for the lack of details in my feedback.
> 
> * I was using supabase cloud database.
> * By default supabase offers connection URI for transaction mode, with port 6543.
> * When using port 6543, `npx prisma migrate dev` does not work.
> * The only clue I found that the connection should be in session mode (port 5432) is by checking docker files in the root dir.
> 
> There were no errors, which cause the confusion. Prisma would display the connection URI in the terminal and that would be it.
> 
> The documentation you linked to would be the saving grace in this situation. Maybe it's worth adding the link to the "getting started" page as a lot of people would like to use supabase, especially for small saas.

I have updated the getting started doc using Supabase as DB option with a link to the Supabase documentation, thanks again for your feedback and feel free to reach out for any other questions!
